### PR TITLE
Useful Features & Fixes

### PR DESCRIPTION
**Pull request by piotr25691**
Adds a bunch of features that match Twitter

### CODE REVIEW

**Comment by Ketchupchh** [comment]
Why are you [hardcoding](https://github.com/ccrsxx/twitter-clone/commit/a366f982d5bc171bd7bb51f29783124f520aac39) the width and height when it should be determined by pictureSize?

**Comment by piotr25691** [comment]
> Why are you [hardcoding](https://github.com/ccrsxx/twitter-clone/commit/a366f982d5bc171bd7bb51f29783124f520aac39) the width and height when it should be determined by pictureSize?

I have removed this since I was having screwy with next.js image components

**Comment by Ketchupchh** [comment]
> > Why are you [hardcoding](https://github.com/ccrsxx/twitter-clone/commit/a366f982d5bc171bd7bb51f29783124f520aac39) the width and height when it should be determined by pictureSize?
> 
> I have removed this since I was having screwy with next.js image components not respecting the square dimensions

Then put flex-none on the component.

**Comment by piotr25691** [comment]
> > > Why are you [hardcoding](https://github.com/ccrsxx/twitter-clone/commit/a366f982d5bc171bd7bb51f29783124f520aac39) the width and height when it should be determined by pictureSize?
> > 
> > I have removed this since I was having screwy with next.js image components not respecting the square dimensions
> 
> Then put flex-none on the component.

I have fixed it by import next/legacy/image instead.

**Comment by Ketchupchh** [comment]
I see you've upgraded the project to Nextjs 14. Are you gonna migrate to the app router?

**Comment by piotr25691** [comment]
I upgraded the code as is, and fixed the breaking layout changes, so probably not.

**Comment by Ketchupchh** [comment]
> image sizing is so pain ngl

Please just do flex-none.

**Comment by Ketchupchh** [comment]
You're using "!" And forcing styles a lot. In my experience, doing that is a band-aid fix and never really fixes the problem. Try finding a more optimal solution?

There's a few questionable changes you've made, some that I think weren't even a problem to begin with. Maybe if you could tell me where your head is then I could help you a bit?

It's cool that you upgraded the project to Nextjs 14 but since you're not migrating to app router I've no idea why you've done that.

**Comment by piotr25691** [comment]
I'm just gonna close this I have no idea why I did it either way

**Pull request closed without merging**
