### PR TITLE
Video support.

### PR DESCRIPTION
**Pull request by Ketchupchh**
I added video support and a very simple fix (from my testing) that prevents usernames from being stolen.

Demo: https://twitter-clone-swart-three.vercel.app/

Obviously, the code for video support is in [here](https://github.com/Ketchupchh/twitter-clone/blob/main/src/lib/validation.ts).
I left the original code intact in case I broke something :P

### CODE REVIEW

**Comment by DaniKasti** [comment]
I believe there is a bug with the video audio. If you click on the video there are two audio's playing - one in the background and one in the clicked on version. Not a huge deal. Just something I noticed.  @Ketchupchh

**Comment by Ketchupchh** [comment]
Thank you. I will fix this.

**Comment by ccrsxx** [comment]
I will review it next week @Ketchupchh hehe.

I'll be done with my final semester at uni this week.

**Review by ccrsxx — COMMENTED** [review]
Overall finished the review. I will check if there's any bug before merging it later.

**Comment by Ketchupchh** [comment]
Awesome, thanks!

**Comment by Ketchupchh** [comment]
Take your time man. Life comes first.

**Comment by ccrsxx** [comment]
@Ketchupchh Can you check the preview? Just wanted to see if everything works. It works fine on my end. If there's no problem I can merge it.

**Comment by Ketchupchh** [comment]
@ccrsxx Everything works fine on desktop. On mobile I was able to load my video but not yours and the image modal never loaded the video either.

**Comment by ccrsxx** [comment]
Damn, I forgot to test it on mobile. I'll take a look later, bruh I thought I could merge it yesterday.

**Comment by ccrsxx** [comment]
Btw I just checked again, it's just the modal that's not coming out on mobile. I'm able to see your video tho.

Hmm, should we add a button on the video on mobile to open the modal or keep it this way? I see that Twitter doesn't open the modal when you click on a video.

**Comment by Ketchupchh** [comment]
Yeah, we should probably add a button to keep the Twitter theme quality.

**Comment by ccrsxx** [comment]
@Ketchupchh I added a button to open the video modal on mobile, but not on desktop since you open the modal by clicking the video there. 

I think it's okay to merge it now, can you check it hehe?

**Comment by Ketchupchh** [comment]
The video modal just infinite loads for me :(. Maybe it's just a problem on my end? :p

**Comment by Ketchupchh** [comment]
I doubt it? My own video also causes the modal to infinite load.

**Comment by ccrsxx** [comment]
Hmm works fine on my end, even using another account that's not an admin.

image

Can you check the web console, and see if there's any error there?

**Comment by Ketchupchh** [comment]
Sorry, I should've mentioned it infinite loads on mobile. Desktop works just fine.

**Comment by ccrsxx** [comment]
Works fine on my phone.

Screenshot_20240303_234939_Samsung Internet

Maybe there's some ad block/extension that blocks the video? Have you tried it on another browser, to see if it works?

**Comment by Ketchupchh** [comment]
Yeah, I've tried it on Safari and OperaGX. Has to be something on my end since for some reason on mobile your video fails to load all together but on desktop it loads fine except the video doesn't show just the audio. imageimage

**Comment by ccrsxx** [comment]
Check the web console on the desktop, is there any errors there?

I'll ask my friends to check the video tomorrow, if it's working, then it must be from your end.

**Comment by Ketchupchh** [comment]
This is all I get. Probably is just an issue on my end. image

**Comment by ccrsxx** [comment]
I think it's a Safari issue, I remember something broke from my website on Safari but not on other browsers.

Can you try using the Chrome browser on your desktop? Don't try it on your iPhone, because all the browsers there are just a custom skin for Safari lol.

**Comment by Ketchupchh** [comment]
Okay yeah, Chrome makes everything work fine lol.

**Comment by ccrsxx** [comment]
Nice, will close this PR tonight.

**Review by ccrsxx — APPROVED** [review]

**Pull request merged**
