### PR TITLE
Feature: Firebase Emulators support

### PR DESCRIPTION
**Pull request by Goku-kun**
Hey, @ccrsxx!

Re-opening a new PR to close #26 and #22 . I'm not sure if it's caught up to all the commits in the previous PRs. Can you take a look at the changes that you've made and confirm if they're? Pretty sure they aren't because I don't see the work about the environment variables switch that we talked about in the commit history.

### CODE REVIEW

**Comment by ccrsxx** [comment]
Yeah, I have to push my previous commits back. For some reason, the previous pr got screwed even tho I push the latest commits I made.

I got a permission issue, then I did the push -f, I already made sure that I was not behind any commits before I did it, but yeah it removed the entire commits on the lol. I'd never use `-f` flag again when pushing lol.

**Comment by Goku-kun** [comment]
Now I feel like trying out the `-f` flag honestly. :rofl:

**Comment by ccrsxx** [comment]
> Now I feel like trying out the `-f` flag honestly. 🤣
> 
> Edit: Also I noticed you're a Re:zero fan. I was a Emilia fan too back in 2017, I guess. Dropped Re:zero manga in 2018 and haven't had the time to go back to it. How is it?

It's Arc 8 now in web novel, basically Season 6 in anime. Don't even bother reading the manga, as it's still behind the Anime lol even now, it's not even finished covering Arc 4 / Season 2 of the Anime, which was released in 2020.

If you dropped the manga back in 2018, then you already watched season 1 right? the story gets better in Season 2, here you'll get some info about the world-building, new characters, some good character development, and obviously more suffering for Subaru 😄 .

If you plan to continue on the series after watching season 2, I suggest you read Light novel starting from volume 15.

As for future seasons, the story continues to be good. Can't explain it in detail because the story is very long lol.

**Comment by ccrsxx** [comment]
Once again, @Goku-kun thanks for the PR. Sorry, it took me so long to close it lol.

**Comment by ccrsxx** [comment]
@Goku-kun Do you read the manga? Ruby currently plays a huge role in the story. Not to mention she's kinda winning on the ship LOL. She's my favorite character in the manga, Akane was previously my favorite, but Ruby takes her place.

**Comment by Goku-kun** [comment]
Ah, no. The adaptation is so fantastic that I don't want to read the manga. On the other hand, I couldn't control myself and read through to the current chapter of JJK in the past. The wait for the anime adaptation was too long. The anime will take 4-5 years to catch up to the current Gojo fight but sheesh.... The manga didn't disappoint at all. Same for One Piece. I read till the end of Wano arc in August 2022 but the anime still hasn't ended the arc after more than a year. For Oshi no Ko, I'm gonna wait. There's a new manga that started recently on Shounen Jump called Kagurabachi. If you're into darker themes, I think you'll enjoy this one so much!

**Pull request merged**
